# Generated by Django 5.1.1 on 2024-09-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_task_user_id_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='User_id',
            new_name='user',
        ),
    ]
